default:
  image: python:3.7
  before_script:
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate
    - pip install -r requirements-test.txt
  cache:
    key: shared
    paths:
      - .cache/pip
      - .venv

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


tests:
  stage: test
  script:
    - pip install -r requirements-plugins.txt
    - make test-verbose

test-coverage:
  stage: test
  script:
    - pip install -r requirements-plugins.txt
    - make coverage coverage-html
  artifacts:
    paths:
      - "htmlcov/*"

type-coverage:
  stage: test
  script:
    - pip install lxml
    - make coverage-typing
  artifacts:
    paths:
      - "mypy-coverage/*"
