server: irc.libera.chat
port: 6697
ssl: true

logging:
  version: 1
  root:
    level: INFO
    handlers:
      - console
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      stream: ext://sys.stdout
  formatters:
    console:
      format: "%(asctime)s %(levelname)s:%(name)s: %(message)s"
      datefmt: "%H:%M:%S"

bot:
  nick: SoupBot
  name: A pluggable IRC bot
  sqlite_db: bot.db

admins: &admins
  - "~vifon@example.com"

plugins:
  - irc.plugins.pong.PongPlugin
  - irc.plugins.watchdog.Watchdog:
      timeout: 300
  - irc.plugins.channels.ChannelManager:
      channels:
        - '#example'
  - irc.plugins.name_track.NameTrack
  - irc.plugins.user_score.UserScore:
      admin: *admins
      scorables:
        - bacon
      max_scoreboard_request: 10
  - irc.plugins.offline_msg.OfflineMessages:
      admin: *admins
      users:
        '#example':
          - example_user
          - vifontest
  - irc.plugins.commandline.Commandline:
      admin: *admins
