server: irc.freenode.net
port: 7000
ssl: true

bot:
  nick: SoupBot
  name: A pluggable IRC bot
  sqlite_db: bot.db

admins: &admins
  - "~vifon@example.com"

plugins:
  - irc.plugins.pong.PongPlugin
  - irc.plugins.channels.ChannelManager:
      channels:
        - '#example'
  - irc.plugins.name_track.NameTrack
  - irc.plugins.user_score.UserScore:
      admin: *admins
      scorables:
        - bacon
      max_scoreboard_request: 10
  - irc.plugins.offline_msg.OfflineMessages:
      admin: *admins
      users:
        '#example':
          - example_user
          - vifontest
  - irc.plugins.commandline.Commandline:
      admin: *admins
