server: irc.freenode.net
port: 7000

bot:
  nick: Wydrek
  name: A pluggable IRC bot
  sqlite_db: bot.db

plugins:
  - irc.plugins.pong.PongPlugin
  - irc.plugins.join.JoinChannels:
      channels:
        - '#example'
  - irc.plugins.name_track.NameTrack
  - irc.plugins.user_score.UserScore:
      admin: vifon
      scorables:
        - bacon
  - irc.plugins.offline_msg.OfflineMessages:
      users:
        - example_user
        - vifontest
