server: 127.0.0.1
port: 6667
ssl: false

logging:
  version: 1
  root:
    level: DEBUG
    handlers:
      - console
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      stream: ext://sys.stdout
  formatters:
    console:
      format: "%(asctime)s %(levelname)s:%(name)s: %(message)s"
      datefmt: "%H:%M:%S"

bot:
  nick: TestBot
  name: A pluggable IRC bot, test instance
  sqlite_db: ":memory:"
  delay: 0

admins: &admins
  - "testadmin@localhost"

plugins:
  - irc.plugins.pong.PongPlugin
  - irc.plugins.channels.ChannelManager:
      channels:
        - '#test-channel1'
        - '#test-channel2'
  - irc.plugins.name_track.NameTrack
  - irc.plugins.user_score.UserScore:
      admin: *admins
      scorables:
        - bacon
      max_scoreboard_request: 10
  - irc.plugins.offline_msg.OfflineMessages:
      admin: *admins
      users:
        '#test-channel1':
          - offline_user
  - irc.plugins.commandline.Commandline:
      admin: *admins
  - irc.plugins.http_preview.HTTPPreview:
      timeout: 1
